sudo: required
dist: trusty
language: node_js
node_js:
  - "12"
script: "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: public
  target_branch: pages
  github_url: github.ibm.com
  on:
    branch: develop
notifications:
  email: false